#!/bin/bash

PYTHON_VERSION="$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

if [[ "$PYTHON_VERSION" != "3.13" ]]; then
    echo "Error: Python 3.13 is required. Found Python ${PYTHON_VERSION}."
    exit 1
fi

echo "Install dependencies"
pip install -r requirements.txt

python manage.py makemigrations
python manage.py migrate
